### ISSUE TITLE
Type hinting according to PEP 585 only available since python 3.9

### ISSUE THREAD

**Issue by xrotwang** [fmatter/pyradigms#2]
The variant of type hinting used in pyradigms ([PEP 585](https://www.python.org/dev/peps/pep-0585/)) has only been introduced in python 3.9. Either `setup.py` should declare the package incompatible with earlier Pythons or `typing.List` etc should be used for annotations.

**Comment by fmatter** [comment]
Does [this](https://github.com/fmatter/pyradigms/commit/5956f330ecdd9f1f820de6beb11a4fd6b63a7548) address the issue? `tox` successfully runs on 3.6-3.8.

**Comment by xrotwang** [comment]
yes.
